version: '2'

services:
  postgresql:
    #image: 'c2corg_pgsql'
    image: 'camptocamp/postgis'
    container_name: 'gmlas_postgresql'
    volumes:
    - ./volumes/pgsql:/var/lib/postgresql/data
    ports:
    - 127.0.1.7:5434:5432

  qgis:
    container_name: gmlas_qgis
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./volumes/qgis:/home/qgis  # qgis home
      - /home/amorvan/.docker.xauth:/home/qgis/.docker.xauth

      #- /home/amorvan/dev/QGIS_Plugins/gmlas:/root/.qgis3/python/plugins/gmlas
      - ./src/gml_application_schema_toolbox/gml_application_schema_toolbox:/home/qgis/.qgis3/python/plugins/gml_application_schema_toolbox
      - /home/amorvan/.qgis-dev/python/plugins/plugin_reloader:/home/qgis/.qgis3/python/plugins/plugin_reloader
      - /home/amorvan/dev/QGIS/python/plugins/processing:/home/qgis/.qgis3/python/plugins/processing
      # - /home/amorvan/dev/QGIS/python/plugins/db_manager:/root/.qgis3/python/plugins/db_manager

      - ./src/gml_application_schema_toolbox/samples:/home/qgis/qgisgmlas/data/samples

    environment:
      - DISPLAY
      - XAUTHORITY=/home/qgis/.docker.xauth
      - PGHOST=postgresql
      - PGDATABASE=gmlas
      - PGUSER=gmlas
      - PGPASSWORD=gmlas
    links:
      - postgresql
    command: /usr/bin/qgis
